// Stage 3: the reporter's crib sheet. Grounded strictly on the transcript,
// generated by the local LLM — quotes are mapped back to timestamps so the
// journalist can jump to the exact moment in the audio.
import { complete } from './qvac.js';

const SYS = `You are a careful newsroom assistant. Work only from the transcript you are given; never invent facts.
Reply in exactly this format, with these four section headers:
[SUMMARY]
[CLAIMS]
[QUOTES]
[FOLLOW-UPS]
[SUMMARY]: 2-3 sentences describing what the source says.
[CLAIMS]: the key factual claims, one per line, each line starting with "- ".
[QUOTES]: up to 4 direct quotes copied exactly from the transcript, one per line, each starting with "> ".
[FOLLOW-UPS]: three short questions a journalist should ask next, one per line, each starting with "- ".`;

const norm = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

export async function generateBrief(segments, modelKey, onEvent = () => {}) {
  const fullText = segments.map((s) => s.text).join('\n');
  onEvent({ phase: 'status', message: 'Writing the source brief locally…' });
  const answer = await complete(modelKey, SYS, `TRANSCRIPT:\n"""\n${fullText.slice(0, 6000)}\n"""`);
  const brief = parseBrief(answer);

  const normSegments = segments.map((s) => ({ startMs: s.startMs, norm: norm(s.text) }));
  brief.quotes = (brief.quotes ?? []).map((q) => {
    const head = norm(q).slice(0, 40);
    const seg = head.length > 8 ? normSegments.find((s) => s.norm.includes(head)) : null;
    return { text: q, startMs: seg ? seg.startMs : null };
  });
  return { summary: brief.summary, claims: brief.claims, quotes: brief.quotes, followups: brief.followups, raw: answer, at: Date.now() };
}

function parseBrief(text) {
  const grab = (name, next) => {
    const re = new RegExp(`\\[${name}\\]([\\s\\S]*?)(?=\\[${next}\\]|$)`, 'i');
    return (text.match(re)?.[1] ?? '').trim();
  };
  const lines = (s) =>
    s
      .split('\n')
      .map((l) => l.replace(/^[-*>•\d.)\s]+/, '').trim())
      .filter(Boolean);

  const summary = grab('SUMMARY', 'CLAIMS').trim();
  const claims = lines(grab('CLAIMS', 'QUOTES'));
  const quotes = lines(grab('QUOTES', 'FOLLOW-UPS'));
  const followups = lines(grab('FOLLOW-UPS', 'END'));

  if (!summary && !claims.length) {
    // Small model went off-script: keep the raw text so nothing is silently lost.
    return { summary: text.slice(0, 600), claims: [], quotes: [], followups: [] };
  }
  return { summary, claims, quotes, followups };
}
